apiVersion: v1
kind: ConfigMap
metadata:
  name: joylive-webhook-config
  namespace: {{ .Values.namespace }}
data:
  {{- $root := . }}
  {{- range $path, $_ :=  .Files.Glob "config/*" }}
  {{- $fileName := base $path }}
  {{ $fileName }}: |
{{ $.Files.Get $path | indent 4 }}
  {{- end }}