apiVersion: apps/v1
kind: Deployment
metadata:
  name: joylive-webhook
  namespace: {{ .Values.namespace }}
  labels:
    app: joylive-webhook
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: joylive-webhook
  template:
    metadata:
      labels:
        app: joylive-webhook
    spec:
      serviceAccountName: joylive-webhook
      containers:
        - env:
            - name: log.level
              value: {{ .Values.logLevel }}
          name: joylive-injector
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
             {{- toYaml .Values.containerArgs | nindent 12 }}
          livenessProbe:
            httpGet:
              scheme: HTTPS
              port: 443
              path: /livez
            periodSeconds: 10
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              scheme: HTTPS
              port: 443
              path: /readyz
            periodSeconds: 10
            initialDelaySeconds: 5
          volumeMounts:
            {{- toYaml .Values.VolumeMounts | nindent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- toYaml .Values.Volumes | nindent 8 }}
