apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "joylive-webhook.name" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - events
      - configmaps
      - namespaces
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - "*"
  - apiGroups:
      - autoscaling
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "joylive-webhook.name" . }}
  namespace: {{ .Values.namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "joylive-webhook.name" . }}
  namespace:  {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "joylive-webhook.name" . }}
    namespace:  {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "joylive-webhook.name" . }}