apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: dynamic-admission-control-certs
  namespace: {{ .Values.namespace }}
data:
  dac-key.pem: {{ .Values.caKeyBundle }}
  dac.pem: {{ .Values.caPubBundle }}

