/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	injectorv1 "github.com/jd-opensource/joylive-injector/client-go/apis/injector/v1"
	versioned "github.com/jd-opensource/joylive-injector/client-go/clientset/versioned"
	internalinterfaces "github.com/jd-opensource/joylive-injector/client-go/informers/externalversions/internalinterfaces"
	v1 "github.com/jd-opensource/joylive-injector/client-go/listers/injector/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AgentVersionInformer provides access to a shared informer and lister for
// AgentVersions.
type AgentVersionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.AgentVersionLister
}

type agentVersionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAgentVersionInformer constructs a new informer for AgentVersion type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAgentVersionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAgentVersionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAgentVersionInformer constructs a new informer for AgentVersion type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAgentVersionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExampleV1().AgentVersions(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExampleV1().AgentVersions(namespace).Watch(context.TODO(), options)
			},
		},
		&injectorv1.AgentVersion{},
		resyncPeriod,
		indexers,
	)
}

func (f *agentVersionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAgentVersionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *agentVersionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&injectorv1.AgentVersion{}, f.defaultInformer)
}

func (f *agentVersionInformer) Lister() v1.AgentVersionLister {
	return v1.NewAgentVersionLister(f.Informer().GetIndexer())
}
