apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Values.namespace }}
  labels: {{ include "joylive-injector.selectorLabels" . | nindent 4 }}
data:
  {{- $root := . }}
  {{- range $path, $_ :=  .Files.Glob "config/*" }}
  {{- $fileName := base $path }}
  {{ $fileName }}: |
{{ $.Files.Get $path | indent 4 }}
  {{- end }}