apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Values.namespace }}
  labels: {{ include "joylive-injector.selectorLabels" . | nindent 4 }}
data:
  {{- $root := . }}
  {{- range $path, $_ :=  $root.Files.Glob "config/*" }}
  {{- $fileName := base $path }}
  {{ $fileName }}: |
{{- $fileContent := $root.Files.Get $path }}
{{- $parsedContent := tpl $fileContent $root }}
{{ $parsedContent | indent 4 -}}
  {{- end }}