apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "joylive-injector.name" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - events
      - configmaps
      - namespaces
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - "*"
  - apiGroups:
      - autoscaling
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - injector.joylive.io
    resources:
      - agentversions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - injector.joylive.io
    resources:
      - agentversions/finalizers
    verbs:
      - update
  - apiGroups:
      - injector.joylive.io
    resources:
      - agentversions/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "joylive-injector.name" . }}
  namespace: {{ .Values.namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "joylive-injector.name" . }}
  namespace:  {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "joylive-injector.name" . }}
    namespace:  {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "joylive-injector.name" . }}