agent:
  enhance:
    javaVersion: '[,1.8);[1.8.0_60,]'
    retransformEnabled: true
    loggerEnabled: true
    exporterEnabled: false
    excludePrefixes: null
    excludeTypes: null
    excludeInterfaces: null
    excludeClassLoaders:
      - com.jd.jr.sgm.agent.loader.ClientLibClassLoader
      - com.jd.pfinder.profiler.load.InterceptorClassLoader
      - com.jd.pfinder.profiler.utils.ModuleClassLoader
      - com.jd.pfinder.profiler.load.ModuleInterceptorClassLoader
      - io.opentelemetry.javaagent.bootstrap.AgentClassLoader
      - org.apache.skywalking.apm.agent.core.plugin.loader.AgentClassLoader
      - org.apache.skywalking.apm.agent.core.plugin.loader.PluginClassLoader
      - com.navercorp.pinpoint.bootstrap.classloader.AgentClassLoader
      - com.navercorp.pinpoint.bootstrap.classloader.PluginClassLoader
      - com.huaweicloud.sermant.core.classloader.FrameworkClassLoader
      - com.huaweicloud.sermant.core.plugin.classloader.PluginClassLoader
      - com.huaweicloud.sermant.core.plugin.classloader.ServiceClassLoader
      - com.alipay.sofa.ark.container.service.classloader.PluginClassLoader
  publisher:
    configs:
      traffic:
        capacity: 20000
  plugin:
    systems:
      - system
    statics:
      - dubbo
      - grpc
      - httpclient
      - jdk
      - jmq
      - jsf
      - kafka
      - okhttp
      - netty
      - phevos
      - rocketmq
      - shenyu
      - sofarpc
      - spring
      - mariadb
      - mongodb
      - opengauss
      - postgresql
      - redis
    disables: null
    dynamics: null
    profiles:
      test: null
      production: null
    profile: null
  sync:
    liveSpace:
      type: ${CONFIG_LIVE_SPACE_API_TYPE:{{ .Values.agent.sync.liveSpace.type }}} # [file,multilive,multilive-openapi,nacos]
      url: ${CONFIG_LIVE_SPACE_API_URL:{{ .Values.agent.sync.liveSpace.url }}}
      service: true
      interval: 5000
      timeout: 3000
      initialTimeout: 20000
      delay: 0
      fault: 5000
      headers: ${CONFIG_LIVE_SPACE_API_HEADERS}
      # for multilive
      multilive:
        spacesUrl: /workspaces
        spaceUrl: /workspaces/${space_id}/version/${space_version}
        serviceUrl: /services/${service_name}/version/${service_version}
      # for multilive-openapi
      jdcloud:
        accessKey: ${CONFIG_MULTILIVE_ACCESS_KEY:{{ .Values.agent.sync.liveSpace.jdcloud.accessKey }}}
        secretKey: ${CONFIG_MULTILIVE_SECRET_KEY:{{ .Values.agent.sync.liveSpace.jdcloud.secretKey }}}
      # for nacos
      nacos:
        username: ${CONFIG_NACOS_USERNAME:nacos}
        password: ${CONFIG_NACOS_PASSWORD:nacos}
        namespace: ${CONFIG_NACOS_NAMESPACE:public}
        liveSpaceGroup: ${CONFIG_NACOS_GROUP_LIVE_SPACE:DEFAULT_GROUP}
        liveSpacesKey: ${CONFIG_NACOS_KEY_LIVE_SPACES:govern-liveSpaces}
        liveSpaceKeyTemplate: ${CONFIG_NACOS_KEY_LIVE_SPACE_TEMPLATE:govern-liveSpace-${id}}
        liveServiceTemplate: ${CONFIG_NACOS_KEY_LIVE_SERVICE_TEMPLATE:govern-liveService-${name}}
    laneSpace:
      type: ${CONFIG_LANE_SPACE_API_TYPE:{{ .Values.agent.sync.lane.type }}} # [file,jmsf,nacos]
      url: ${CONFIG_LANE_SPACE_API_URL:{{ .Values.agent.sync.lane.url }}}
      # for jmsf
      jmsf:
        spacesUrl: /laneSpaces
        spaceUrl: /laneSpace/${space_id}/version/${space_version}
      # for nacos
      nacos:
        username: ${CONFIG_NACOS_USERNAME:nacos}
        password: ${CONFIG_NACOS_PASSWORD:nacos}
        namespace: ${CONFIG_NACOS_NAMESPACE:public}
        laneSpaceGroup: ${CONFIG_NACOS_GROUP_LANE_SPACE:DEFAULT_GROUP}
        laneSpacesKey: ${CONFIG_NACOS_KEY_LANE_SPACES:govern-laneSpaces}
        laneSpaceKeyTemplate: ${CONFIG_NACOS_KEY_LANE_SPACE_TEMPLATE:govern-laneSpace-${id}}
    microservice:
      type: ${CONFIG_SERVICE_API_TYPE:{{ .Values.agent.sync.microservice.type }}} # [file,jmsf,nacos]
      url: ${CONFIG_SERVICE_API_URL:{{ .Values.agent.sync.microservice.url }}}
      headers: ${CONFIG_SERVICE_API_HEADERS}
      interval: 5000
      timeout: 3000
      initialTimeout: 20000
      # for jmsf
      jmsf:
        serviceUrl: /space/${space}/service/${service_name}/version/${service_version}?application=${application}
      # for nacos
      nacos:
        username: ${CONFIG_NACOS_USERNAME:nacos}
        password: ${CONFIG_NACOS_PASSWORD:nacos}
        namespace: ${CONFIG_NACOS_NAMESPACE:public}
        serviceGroup: ${CONFIG_NACOS_GROUP_SERVICE:DEFAULT_GROUP}
        serviceKeyTemplate: ${CONFIG_NACOS_KEY_SERVICE_TEMPLATE:govern-service-${name}}
  watchdog:
    enabled: true
    delay: 5000
    interval: 100
    timeout: 5000
  switch:
    live:
      enabled: ${CONFIG_LIVE_ENABLED:{{ .Values.agent.switch.live }}}
      mq: ${CONFIG_LIVE_MQ_ENABLED:false}
      dubbo: true
      grpc: true
      sofarpc: true
      jsf: true
      spring: true
      phevos: true
      rocketmq: true
    lane:
      enabled: ${CONFIG_LANE_ENABLED:{{ .Values.agent.switch.lane }}}
    transmission:
      enabled: ${CONFIG_TRANSMISSION_ENABLED:true}
      threadpool: ${CONFIG_TRANSMISSION_THREADPOOL_ENABLED:true}
    registry:
      enabled: ${CONFIG_REGISTRY_ENABLED:true}
    flowcontrol:
      enabled: ${CONFIG_FLOW_CONTROL_ENABLED:{{ .Values.agent.switch.flowcontrol }}}
      localhost: ${CONFIG_LOCALHOST_ENABLED:false}
      virtual: ${CONFIG_VIRTUAL_ENABLED:false}
    protect:
      enabled: ${CONFIG_PROTECT_ENABLED:false}
      mariadb: true
      postgresql: true
      opengauss: true
      mongodb: true
      redis: false
    classloader:
      enabled: ${CONFIG_CLASSLOADER_ENABLED:true}
      springboot: true
    counter:
      enabled: true
  governance:
    initializeTimeout: ${CONFIG_POLICY_INITIALIZE_TIMEOUT:10000}
    service:
      localFirst: ${CONFIG_LOCAL_FIRST:true}
      localFirstMode: ${CONFIG_LOCAL_FIRST_MODE:CELL}
      serviceGroups: ${CONFIG_SERVICE_GROUPS:}
      serviceGroupOpen: ${CONFIG_SERVICE_GROUP_OPEN:true}
      warmups: ${CONFIG_WARMUP_SERVICES:}
      systemPaths: ${CONFIG_SYSTEM_HTTP_PATHS}
      concurrencyLimiter:
        type: Resilience4j
        cleanInterval: 30000
        expireTime: 60000
      rateLimiter:
        type: SmoothBursty
        cleanInterval: 30000
        expireTime: 60000
      loadLimiter:
        cpuUsage: ${CONFIG_MAX_CPU_USAGE:}
        loadUsage: ${CONFIG_MAX_LOAD_USAGE:}
      circuitBreaker:
        type: Resilience4j
        cleanInterval: 30000
        expireTime: 60000
    live:
      fallbackLocationIfNoSpace: ${CONFIG_FALLBACK_LOCATION_IF_NO_SPACE:false}
      topics: ${CONFIG_LIVE_TOPICS}
      modifyMQGroupEnabled: ${CONFIG_LIVE_MODIFY_MQ_GROUP:false}
    lane:
      topics: ${CONFIG_LANE_TOPICS}
      modifyMQGroupEnabled: ${CONFIG_LANE_MODIFY_MQ_GROUP:false}
    router:
      virtual: ${CONFIG_VIRTUAL_SIZE:500}
      spring:
        discovery:
          disables: ${CONFIG_SPRING_DISCOVERY_DISABLES}
      phevos:
        groupExpression: ${unit}-${cell}-${group}
    transmission:
      keys:
        - x-live-space-id
        - x-live-rule-id
        - x-live-uid
        - x-lane-space-id
        - x-lane-code
      prefixes:
        - x-live-
        - x-lane-
        - x-service-
      thread:
        excludeExecutors:
          - org.apache.dubbo.common.threadpool.ThreadlessExecutor
          - org.apache.tomcat.util.threads.ThreadPoolExecutor
          - org.apache.tomcat.util.threads.ScheduledThreadPoolExecutor
          - org.apache.tomcat.util.threads.InlineExecutorService
          - javax.management.NotificationBroadcasterSupport$1
          - io.grpc.stub.ClientCalls.ThreadlessExecutor
          - io.grpc.SynchronizationContext
          - io.netty.channel.MultithreadEventLoopGroup
          - io.netty.channel.nio.NioEventLoop
          - io.netty.channel.SingleThreadEventLoop
          - io.netty.channel.kqueue.KQueueEventLoopGroup
          - io.netty.channel.kqueue.KQueueEventLoop
          - io.netty.util.concurrent.MultithreadEventExecutorGroup
          - io.netty.util.concurrent.AbstractEventExecutorGroup
          - io.netty.util.concurrent.ThreadPerTaskExecutor
          - io.netty.util.concurrent.GlobalEventExecutor
          - io.netty.util.concurrent.AbstractScheduledEventExecutor
          - io.netty.util.concurrent.AbstractEventExecutor
          - io.netty.util.concurrent.DefaultEventExecutor
          - io.netty.util.concurrent.SingleThreadEventExecutor
          - io.netty.util.internal.ThreadExecutorMap$1
          - reactor.core.scheduler.BoundedElasticScheduler$BoundedScheduledExecutorService
          - reactor.netty.resources.ColocatedEventLoopGroup
          - com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoopGroup
          - com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.MultithreadEventLoopGroup
          - com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.concurrent.MultithreadEventExecutorGroup
          - com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutorGroup
          - com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.concurrent.ThreadPerTaskExecutor
          - com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.concurrent.GlobalEventExecutor
          - com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.concurrent.AbstractScheduledEventExecutor
          - com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor
          - com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop
          - com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.SingleThreadEventLoop
          - com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor
          - com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$1
          - com.alibaba.nacos.shaded.io.grpc.internal.ManagedChannelImpl$ExecutorHolder
          - com.alibaba.nacos.shaded.io.grpc.internal.ManagedChannelImpl$RestrictedScheduledExecutor
          - com.alibaba.nacos.shaded.io.grpc.internal.ManagedChannelImpl$2
          - com.alibaba.nacos.shaded.io.grpc.internal.SerializingExecutor
          - com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls.ThreadlessExecutor
          - com.alibaba.nacos.shaded.io.grpc.SynchronizationContext
          - com.alibaba.nacos.shaded.com.google.common.util.concurrent.DirectExecutor
        excludeTasks:
          - com.alibaba.nacos.shaded.io.grpc.internal.DnsNameResolver.Resolve
          - com.alibaba.nacos.client.naming.backups.FailoverReactor$DiskFileWriter
          - com.alibaba.nacos.client.naming.backups.FailoverReactor.SwitchRefresher
          - com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask
          - com.alibaba.nacos.shaded.io.grpc.internal.DnsNameResolver$Resolve
          - com.alibaba.nacos.shaded.io.grpc.internal.DelayedClientTransport$5
          - com.alibaba.nacos.shaded.io.grpc.internal.SerializingExecutor
          - com.alibaba.nacos.shaded.io.grpc.internal.LogExceptionRunnable
          - com.jd.live.agent.core.thread.NamedThreadFactory
          - com.jd.jr.sgm.client.disruptor.LogEventFactory
        excludeTaskPrefixes:
          - reactor.core.scheduler.BoundedElasticScheduler$$Lambda
          - org.springframework.cloud.commons.util.InetUtils$$Lambda$
          - com.alibaba.nacos.client.auth.ram.identify.CredentialWatcher$
          - com.alibaba.nacos.client.naming.backups.FailoverReactor$$Lambda$
          - com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate$$Lambda$
          - com.alibaba.nacos.common.remote.client.RpcClient$$Lambda$
          - com.alibaba.nacos.common.utils.ThreadFactoryBuilder$$Lambda$
          - sun.rmi.transport.tcp.TCPTransport$
          - sun.rmi.transport.DGCImpl$
          - sun.rmi.transport.DGCAckHandler$
  counter:
    gateway: true
    service: true
    readerInterval: 1000
    exporter:
      type: ${CONFIG_COUNTER_EXPORTER_TYPE:{{ .Values.agent.exporter.type }}}
      endpoint: ${CONFIG_COUNTER_EXPORTER_ENDPOINT:{{ .Values.agent.exporter.endpoint }}}
      timeout: 5000
