# Define the version, environment variables, and other information of joylive-injector injecting joylive-agent
agent:
  image: {{ .Values.agent.image.repository }}
  version: {{ .Values.agent.image.tag }}
  envs:
    {{- with .Values.agent.envs }}
      {{- toYaml . | nindent 4 }}
    {{- else }}
    JAVA_TOOL_OPTIONS: -javaagent:/joylive/live.jar
    {{- end }}