# Define the version, environment variables, and other information of joylive-injector injecting joylive-agent
agent:
  image: {{ .Values.agent.image.repository }}
  version: {{ .Values.agent.image.tag }}
  env:
    JAVA_TOOL_OPTIONS: -javaagent:/joylive/live.jar