/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AgentVersionSpecApplyConfiguration represents an declarative configuration of the AgentVersionSpec type for use
// with apply.
type AgentVersionSpecApplyConfiguration struct {
	Version       *string `json:"version,omitempty"`
	ConfigMapName *string `json:"configMapName,omitempty"`
	Enable        *bool   `json:"enable,omitempty"`
}

// AgentVersionSpecApplyConfiguration constructs an declarative configuration of the AgentVersionSpec type for use with
// apply.
func AgentVersionSpec() *AgentVersionSpecApplyConfiguration {
	return &AgentVersionSpecApplyConfiguration{}
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *AgentVersionSpecApplyConfiguration) WithVersion(value string) *AgentVersionSpecApplyConfiguration {
	b.Version = &value
	return b
}

// WithConfigMapName sets the ConfigMapName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigMapName field is set to the value of the last call.
func (b *AgentVersionSpecApplyConfiguration) WithConfigMapName(value string) *AgentVersionSpecApplyConfiguration {
	b.ConfigMapName = &value
	return b
}

// WithEnable sets the Enable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enable field is set to the value of the last call.
func (b *AgentVersionSpecApplyConfiguration) WithEnable(value bool) *AgentVersionSpecApplyConfiguration {
	b.Enable = &value
	return b
}
