/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/jd-opensource/joylive-injector/client-go/apis/injector/v1"
	injectorv1 "github.com/jd-opensource/joylive-injector/client-go/applyconfiguration/injector/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAgentVersions implements AgentVersionInterface
type FakeAgentVersions struct {
	Fake *FakeExampleV1
	ns   string
}

var agentversionsResource = v1.SchemeGroupVersion.WithResource("agentversions")

var agentversionsKind = v1.SchemeGroupVersion.WithKind("AgentVersion")

// Get takes name of the agentVersion, and returns the corresponding agentVersion object, and an error if there is any.
func (c *FakeAgentVersions) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.AgentVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(agentversionsResource, c.ns, name), &v1.AgentVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.AgentVersion), err
}

// List takes label and field selectors, and returns the list of AgentVersions that match those selectors.
func (c *FakeAgentVersions) List(ctx context.Context, opts metav1.ListOptions) (result *v1.AgentVersionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(agentversionsResource, agentversionsKind, c.ns, opts), &v1.AgentVersionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.AgentVersionList{ListMeta: obj.(*v1.AgentVersionList).ListMeta}
	for _, item := range obj.(*v1.AgentVersionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested agentVersions.
func (c *FakeAgentVersions) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(agentversionsResource, c.ns, opts))

}

// Create takes the representation of a agentVersion and creates it.  Returns the server's representation of the agentVersion, and an error, if there is any.
func (c *FakeAgentVersions) Create(ctx context.Context, agentVersion *v1.AgentVersion, opts metav1.CreateOptions) (result *v1.AgentVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(agentversionsResource, c.ns, agentVersion), &v1.AgentVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.AgentVersion), err
}

// Update takes the representation of a agentVersion and updates it. Returns the server's representation of the agentVersion, and an error, if there is any.
func (c *FakeAgentVersions) Update(ctx context.Context, agentVersion *v1.AgentVersion, opts metav1.UpdateOptions) (result *v1.AgentVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(agentversionsResource, c.ns, agentVersion), &v1.AgentVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.AgentVersion), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAgentVersions) UpdateStatus(ctx context.Context, agentVersion *v1.AgentVersion, opts metav1.UpdateOptions) (*v1.AgentVersion, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(agentversionsResource, "status", c.ns, agentVersion), &v1.AgentVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.AgentVersion), err
}

// Delete takes name of the agentVersion and deletes it. Returns an error if one occurs.
func (c *FakeAgentVersions) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(agentversionsResource, c.ns, name, opts), &v1.AgentVersion{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAgentVersions) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(agentversionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.AgentVersionList{})
	return err
}

// Patch applies the patch and returns the patched agentVersion.
func (c *FakeAgentVersions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.AgentVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(agentversionsResource, c.ns, name, pt, data, subresources...), &v1.AgentVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.AgentVersion), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied agentVersion.
func (c *FakeAgentVersions) Apply(ctx context.Context, agentVersion *injectorv1.AgentVersionApplyConfiguration, opts metav1.ApplyOptions) (result *v1.AgentVersion, err error) {
	if agentVersion == nil {
		return nil, fmt.Errorf("agentVersion provided to Apply must not be nil")
	}
	data, err := json.Marshal(agentVersion)
	if err != nil {
		return nil, err
	}
	name := agentVersion.Name
	if name == nil {
		return nil, fmt.Errorf("agentVersion.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(agentversionsResource, c.ns, *name, types.ApplyPatchType, data), &v1.AgentVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.AgentVersion), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeAgentVersions) ApplyStatus(ctx context.Context, agentVersion *injectorv1.AgentVersionApplyConfiguration, opts metav1.ApplyOptions) (result *v1.AgentVersion, err error) {
	if agentVersion == nil {
		return nil, fmt.Errorf("agentVersion provided to Apply must not be nil")
	}
	data, err := json.Marshal(agentVersion)
	if err != nil {
		return nil, err
	}
	name := agentVersion.Name
	if name == nil {
		return nil, fmt.Errorf("agentVersion.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(agentversionsResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1.AgentVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.AgentVersion), err
}
